### ISSUE TITLE
System.UnexpectedException: No more than one executeBatch can be called from within a test method

### ISSUE THREAD

**Issue by douglascayers** [DouglasCAyers/sfdc-add-campaign-members-by-report#10]
Reported by [Greg Coogan](https://douglascayers.com/2017/01/22/automate-adding-campaign-members-via-reports/comment-page-1/#comment-2167):

> Getting this error when running tests in Production on “AddCampaignMembersByReportBatchableTest”:
>
> System.UnexpectedException: No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation.
Stack Trace: External entry point
>
> Do we have a fix?

**Comment by douglascayers** [comment]
Yes, that test class runs the report **Add_Contacts_To_Campaign_Test**. You will need to modify its filters to ensure only a handful of records are found.

Unfortunately, with the Analytics API in Apex the tests always run with “seeAllData = true” regardless if we want it to or not. To control the amount of data the test crunches on you can widen or narrow the filters on that report.

**Comment by douglascayers** [comment]
I'll look at modifying the batch class to check if `Test.isRunningTest()` and ensure iterable only has no more than one execute's worth of records.

**Comment by kristin44hubbard** [comment]
What do you mean by "modify its filters to ensure only a handful of records are found."?  The report only pulls 1 record for me, so I'm not sure how to narrow the results down any further.

Thanks!

**Comment by douglascayers** [comment]
Hi @kristin44hubbard,

One reason why the unit test may fail is if the batch job executes more than once (testing limit imposed by Salesforce). When the test runs it runs with access to all data so my hypothesis is that despite when you look at the report in Salesforce and see only 1 record that when the test runs it might see 201+ records.

Can you confirm if the org physically has more than 1 contact, or more specifically, more than 200 contacts?

If it does have more than 1 contact, customize the test report to have criteria that ensures that only 1 contact would ever come back in the report.

Make sense?

**Comment by kristin44hubbard** [comment]
@DouglasCAyers Thank you so much for the explanation!  I updated the report to only pull one contact record, but I'm still getting the errors:
System.AssertException: Assertion Failed: Expected: 2, Actual: 1 
Stack Trace: Class.AddCampaignMembersByReportBatchableTest.test_batchable: line 98, column 1
AND 
System.UnexpectedException: No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. 
Stack Trace: External entry point

Method Name: test_batchable
Class Name: AddCampaignMembersByReportBatchableTest

**Comment by douglascayers** [comment]
Hi @kristin44hubbard,

Hrmm, that line number [98](https://github.com/DouglasCAyers/sfdc-add-campaign-members-by-report/blob/master/src/classes/AddCampaignMembersByReportBatchableTest.cls#L98) doesn't seem to match anything in the current code.

Perhaps try installing the latest managed package option [Release 1.6](https://github.com/DouglasCAyers/sfdc-add-campaign-members-by-report#release-16) and see if that resolves anything.
