### ISSUE TITLE
Contacts not being added to campaigns anymore

### ISSUE THREAD

**Issue by jlucciano** [DouglasCAyers/sfdc-add-campaign-members-by-report#18]
My company has been using the "Add Campaign Members By Report" app successfully in our Salesforce org for some time, but I recently deactivated the Admin who installed the package, as he left the company. 

The reports we are using are scheduled to run every night. The running user is an active Admin, but the process to add the contacts to campaigns doesn't seem to be working anymore - it stopped when I deactivated our old Admin's User account. 

I've been trying to troubleshoot for weeks and I'm at the point where I may just uninstall and reinstall the package. Here are some things I've looked at:

- Assigned the active Sys Admin the "Add Campaign Members by Report Admin" permission set
- Rescheduled the reports to run with the active Sys Admin as the running user 

The only thing I can see that's still under our old/deactivated Admin's user is the fact that the package was installed by him, and the reports being used were created by him, but I assume neither of those things matter. I have not changed the way the "Add Campaign Members by Report Settings" records are set up. 

Any suggestions on other places I can look to troubleshoot?

**Comment by jlucciano** [comment]
As an update, I found your documentation on this site and realized that I should be subscribing to the report rather than scheduling the report to run via an apex job. The subscribe option has the Execute Custom Action = AddCampaignMembersbyReportAction, vs. scheduling the job which did not. I subscribed to it for 7AM tomorrow so fingers crossed that this works and I can close this issue!

**Comment by jlucciano** [comment]
this works now - sorry for the false alarm. The documentation on your page was helpful, I didn't have that before. you can close or delete this :)

**Comment by douglascayers** [comment]
Hi @jlucciano, glad you got it working. I appreciate your updates as you worked through the issue as that is helpful for anyone else you may encounter the same problem.

I'm also glad to hear you're enjoying this solution =)

You might also be interested in my other solution, [Mass Action Scheduler](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki), which is a much more robust and fully featured automation scheduling tool. Also free. The "contacts to campaign" automation is one of my earliest projects and precursor to Mass Action Scheduler.
