### ISSUE TITLE
Idea : Use Contact/Lead ID field name instead of Contact/Lead report label to prevent translation issues

### ISSUE THREAD

**Issue by Pi-Er** [DouglasCAyers/sfdc-add-campaign-members-by-report#2]
Hi Doug,

It could be great to use contact/lead field name instead of the label displayed in the report.
Indeed, I noticed that by using the label, I have issues when switching my default language from French to English (I often do it as an admin).
I set up the custom setting with Contact/Lead ID report label displayed in French and when I switch in English, of course the label have been translated. The consequence is that the custom setting set is not accurate any more and the script can not be run.

Hope this idea will catch your attention.

Have a nice day,

**Comment by douglascayers** [comment]
Great catch here Peter! Initially, my design was thinking what would be the simplest way for the admin to configure in the Custom Setting the field from the report and I figured well, the actual column label displayed on the report. What I failed to realize is that those values change if your language setting changes.

I'm not 100% positive, but will check to see if the report metadata in the code lets me know what the underlying API name of the column is. The Analytics API is a bit funny about what data it provides me.

Thanks,

Doug

**Comment by Pi-Er** [comment]
Hi Douglas!
Thank you for fixing the issue.
I have trouble to understand how to configure the new version : in the custom settings, what name/id/label do I need to use in "Report Contact or Lead ID Column Label" ?
For example, I'm running an report on contact and have the contact id column in my report. Do I need to set "Id" (which is the field name) or something else?

Thank you!

**Comment by Pi-Er** [comment]
Hi again
I talked with my dev and we figured out that we need to use the column name that we can find in the report metadata. 
Thanks Douglas!

**Comment by douglascayers** [comment]
Hi Peter,

Correct, the custom setting now has to be the column name as defined in the Report Metadata. I think for all standard lookup fields it would be **CONTACT_ID** but for custom lookup fields it will be in format [objectName].[fieldName] like **MyObject__c.MyContactField__c**

I haven't yet updated the README to explain all that yet (eek!) but I'm also working on a configuration page to make that all easier so people don't need a developer to dig up the Report Metadata to figure this out.

Thanks!

Doug

**Comment by douglascayers** [comment]
Hi Peter,

I've updated the code tonight. This version now includes a Visualforce page for easier maintenance of the custom settings. No more copy & pasting campaign or report ids and no need for developers to dig into the Report Metadata to know what column name to use. Check out the updated README for more details.

Thanks,

Doug
