### ISSUE TITLE
Returns Error Email

### ISSUE THREAD

**Issue by nickelar** [DouglasCAyers/sfdc-add-campaign-members-by-report#8]
While attempting to subscribe to the report and execute the active for this add on I am choosing the save and run to text that the contacts from the report are added to the campaign. I receive the following error email. 

**An unexpected error occured. Error message: 

This report will no longer be checked for notifications. You can activate the notification in the Report Subscription page.**

I have chosen the Active checkbox and allowed time for the report to run at the schedule time; in which case I have verified that the contacts from the report were not added to the campaign setup in the Add Campaign Members by Report Settings object. Any suggestions you can provide to check where there could be an issue in getting this setup? Thanks

**Comment by douglascayers** [comment]
Hi @nickelar,

Can you provide specifics to reproduce the report you're running? Could you also provide screen shots how you've configured the report to campaign mapping?

Thanks,

Doug

**Comment by nickelar** [comment]
The config setup below -

[image: Inline image 1]
![image](https://cloud.githubusercontent.com/assets/26972242/24801565/c400e6ba-1b72-11e7-9ec5-866d747b8e9e.png)


The Add to Campaign Setup

[image: Inline image 2]
![image](https://cloud.githubusercontent.com/assets/26972242/24801590/df43d45a-1b72-11e7-88d2-ade0c3f583ec.png)

The report setup

Report Type: Oppty w/ Accounts and Contacts
Tabular Format Report
Col 3 = Broker: Contact ID
The broker is a lookup on the oppty record

One thing I noticed when I was typing this email is I have the report saved
in "My Personal Folder" - would that prevent from running?
[image: Inline image 3]
![image](https://cloud.githubusercontent.com/assets/26972242/24801614/f7a2af44-1b72-11e7-85e6-22468372dd80.png)


Let me know if something jumps out at you, I slept on it but nothing is
jumping out at me.

Thanks

**Comment by douglascayers** [comment]
Thanks for the follow up @nickelar. Unfortunately, the images from your email reply were stripped out =(

It is ok for the report to be saved in "My Personal Folder".

**Comment by douglascayers** [comment]
You know what... about "My Personal Folder".... if you're using the latest version of the code from GitHub then I don't think you're able to create a Campaign-Report mapping on the "Add Campaign Members By Report Settings" tab that pulls a report from the personal folder.

Did you setup your mapping via the custom setting directly in Setup menu?

**Comment by douglascayers** [comment]
Hi @nickelar,

I'd released new version, 1.6, of this app. Installation links are available on the project README page. Please upgrade and let me know if you continue to encounter errors. A new tab "Add Campaign Members by Report Logs" is available in the new package that might shed some light on what's happening.

Thanks,

Doug

**Comment by nickelar** [comment]
I edited the original comment with the screen shots.

Thanks

**Comment by nickelar** [comment]
The update corrected what ever the issue was preventing contacts from being added to a campaign. Thanks for you help 👍

**Comment by douglascayers** [comment]
Awesome!
